### ISSUE TITLE
Executing wasm in AOT and JIT mode but got wrong answer?

### ISSUE THREAD

**Issue by Zhangyx24** [bytecodealliance/wasm-micro-runtime#1282]
### Steps to reproduce
I tried to execute the wasm 
[roltest.txt](https://github.com/bytecodealliance/wasm-micro-runtime/files/9076346/roltest.txt)
in AOT and JIT mode in macOS and linux but got the wrong answer.

AOT:
`wamrc -o roltest.aot roltest.wasm`
`iwasm -f _main roltest.aot`

JIT:
`cd product-mini/platforms/darwin/JITbuild/iwasm -f _main roltest.wasm` in mac
and `cd product-mini/platforms/linux/JITbuild/iwasm -f _main roltest.wasm` in linux

### Expected output
4

### Actual output
The actual output is a random number, everytime I excute it I got a different output.

**Comment by wenyongh** [comment]
@Zhangyx24 Thanks for reporting the issue! I submitted PR #1285 to fix it, please try again.

**Comment by Zhangyx24** [comment]
![image](https://user-images.githubusercontent.com/28601300/178216461-af4250ec-ac2d-417d-bdc5-5521a7f47652.png)
 It seems that the commit didn't pass all the tests.
Should I update directly to this COMMIT version locally and test it ?

**Comment by Zhangyx24** [comment]
Besides the roltest.txt, the
 [new_rol_test.txt](https://github.com/bytecodealliance/wasm-micro-runtime/files/9081931/new_rol_test.txt) encounters the same problem.
The expected output is 235, however both AOT and JIT got a random number.

**Comment by wenyongh** [comment]
> @wenyongh
> 
> ![image](https://user-images.githubusercontent.com/28601300/178216461-af4250ec-ac2d-417d-bdc5-5521a7f47652.png) It seems that the commit didn't pass all the tests. Should I update directly to this COMMIT version locally and test it ?

It is due to code guideline issue and has been fixed.

> Besides the roltest.txt, the [new_rol_test.txt](https://github.com/bytecodealliance/wasm-micro-runtime/files/9081931/new_rol_test.txt) encounters the same problem. The expected output is 235, however both AOT and JIT got a random number.

Seems it is the same issue, please rebuild wamrc and test again.

**Comment by Zhangyx24** [comment]
OK, I'm going to try it again, thanks for your answer !

**Comment by Zhangyx24** [comment]
@wenyongh 
I'm sorry that the problem seems not fixed, I still got a random output when I executing roltest.wat in AOT mode.

**Comment by wenyongh** [comment]
Have you rebuilt the wamrc and generated the aot file again?

**Comment by Zhangyx24** [comment]
Yes.

**Comment by wenyongh** [comment]
@Zhangyx24 I tested again in Linux and MacOS, both of your cases work. Could you please check whether this line is executed:
https://github.com/wenyongh/wasm-micro-runtime/blob/fix_aot_rotr_0/core/iwasm/compilation/aot_emit_numberic.c#L695

Or, could you please dump the llvm ir file with command:
```bash
wamrc --format=llvmir-unopt -o test.ll <wasm file>
```

And see whether the content in the end of file is like:
```
func_end:                                         ; preds = %func_begin
  %phi = phi i64 [ 4, %func_begin ]
  ret i64 %phi
}
```

**Comment by wenyongh** [comment]
@Zhangyx24 I uploaded another patch set, could you please try again?

**Comment by Zhangyx24** [comment]
@wenyongh Thanks a lot ! I'm going to try it again.

**Comment by wenyongh** [comment]
Have you rebuilt wamrc and re-generated aot file again? The handling for JIT and AOT should be the same.

**Comment by Zhangyx24** [comment]
Yes, I clone the main branch and rebuild wamrc int the following steps:
![截屏2022-06-21 下午4 22 59](https://user-images.githubusercontent.com/28601300/178459754-ae8d7807-fd63-4226-b0dd-448207d8612b.png)

**Comment by Zhangyx24** [comment]
@wenyongh Sorry, I tried it again. Now it succeed. Thanks a lot!! I'll close this issue.
